spring:
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:postgresql://localhost:5432/gamestore"
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  # Actuator Configuration
  management:
    endpoints:
      web:
        exposure:
          include: "health,info,metrics"
    endpoint:
      health:
        show-details: always